### ISSUE TITLE
This repo has been abandoned by its maintainer.

### ISSUE THREAD

**Issue by dstampher** [3846masa/http-cookie-agent#512]
Issues do not receive responses.  This library does not work with https-proxy-agent, which receives 40 million installs per month.

We need a new repo that will be actively maintained that implements the desired functionality.

**Comment by dstampher** [comment]
Anyone have a good alternative, as this repo does not work with https-proxy-agent?

**Comment by 3846masa** [comment]
Hi, I am 3846masa, a maintainer.

I am sorry for not replying for a long time.

Unfortunately, we are very reluctant to be told that maintenance has been abandoned due to a one month or so of inactivity.

As the MIT License originally states, open source software is provided without any warranty, and users should agree to use it.

Making strong demands to fix it because it doesn't work, or to maintain it, is a terribly arrogant and shameful act.

This software may be freely copied under the MIT License. If you disagree with my opinion, please copy and modify this software yourself.

In the future, if you make another issue like this one with no respect for the maintainer, I will ban your account from this repository.

------

P.S.

This repository has an issue template.
If you create an issue using that template, I will be notified immediately.

I don't know why you didn't use an issue template.
It is clearly wrong for you to contact me by any way other than the one I have provided and then complain that you did not receive a response.
